xendit:
  ewallet:
    ovo:
      invoice: false
      legacy: false
    dana:
      invoice: false
      legacy: false
    linkaja:
      invoice: false
      legacy: false

finpay:
  callback_url: "https://example.com/payment/finpay/callback"
  success_redirect_url: "https://example.com/payment/success"
  failed_redirect_url: "https://example.com/payment/failed"
